import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/props/Navbar";

export const metadata: Metadata = {
  title: "Zyphera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased dark`}
      >
        <NavBar></NavBar>
        {children}
        
      </body>
    </html>
  );
}
